### ISSUE TITLE
When to clear the MO buffer?

### ISSUE THREAD

**Issue by niag-IDSI** [sparkfun/SparkFun_IridiumSBD_I2C_Arduino_Library#12]
I am looking for some help re: clearing the MO buffer.

I understand that when one of the sendSBDText, sendSBDBinary, sendReceiveSBDText, sendReceiveSBDBinary are called, the library does consecutive retries within ISBD_DEFAULT_SENDRECEIVE_TIME seconds. Either there is a timeout, successful transmission or fatal error. This timeout can be adjusted by the adjustSendReceiveTimeout() function.

I have then seen in the send/receive example that after the send/receive functions terminate you always clear the MO buffer. This would make sense in the case when the transmission was successful, but I don't understand why you do it also in the case that it failed. Can't I just call again the send/receive functions without clearing the MO buffer? Is it because when calling them, I have to pass the buffer to be sent?

**Comment by PaulZC** [comment]
Hi @niag-IDSI ,

The Iridium modem does not clear the MO buffer automatically, you have to do it manually. This means that if you send a message (text or binary), that message stays in the MO buffer even if the send was successful. If you then want to check for new MT messages by sending an 'empty' message ( ```modem.sendReceiveSBDText(NULL, buffer, bufferSize);``` ) the message in the MO buffer is re-sent, burning up your message credits. It is safest to clear the MO buffer just in case.

But, yes, if you want to, you could choose not to clear the MO buffer if the send failed. Calling ```modem.sendReceiveSBDText(NULL, buffer, bufferSize);``` would re-send the existing message in the MO buffer.

Best wishes,
Paul
