### ISSUE TITLE
Replace boolean with bool - IridiumSBD::isConnected()

### ISSUE THREAD

**Issue by niag-IDSI** [sparkfun/SparkFun_IridiumSBD_I2C_Arduino_Library#13]
I compiled with PlatformIO (still Arduino platform) and got a warning that `boolean` is deprecated.

Perhaps makes sense to replace with `bool` in the `IridiumSBD::isConnected()` function

**Comment by PaulZC** [comment]
Hello @niag-IDSI ,

Apologies for the _**very**_ slow reply!

This is resolved in v3.0.6.

Very best wishes,
Paul
