### ISSUE TITLE
Receive Data

### ISSUE THREAD

**Issue by giovaniega** [sparkfun/SparkFun_IridiumSBD_I2C_Arduino_Library#14]
To receive data, the method is send a blank MO message, with this method(blank message), it will not consuming the credits, 
but sometimes with same syntax, it send non-empty message, so it consuming the credits,
i dont know why it sometimes send blank message, and sometimes send non-blank message

**Comment by PaulZC** [comment]
Hi @giovaniega ,

You can call ```clearBuffers(ISBD_CLEAR_MO)``` to make sure the Mobile Originated (MO) buffer is clear. The other options are: ```ISBD_CLEAR_MT``` and ```ISBD_CLEAR_BOTH```. Please see the [code examples](https://github.com/sparkfun/SparkFun_IridiumSBD_I2C_Arduino_Library/blob/5f8ea893907ba39e85d665abedc35ac09eb3567d/examples/I2C_Examples__Qwiic_Iridium/Example6_SendReceive/Example6_SendReceive.ino#L146-L153) and [the history](https://github.com/sparkfun/SparkFun_IridiumSBD_I2C_Arduino_Library#history) for more details.

Best wishes,
Paul

**Comment by giovaniega** [comment]
Hi Paul,
Thanks for the answer. I will try it

Pada tanggal Jum, 14 Okt 2022 pukul 15.02 Paul ***@***.***>
menulis:

**Comment by giovaniega** [comment]
Hi Paul,
I'm Giovani, an embedded engineer from Widya Matador,
May i ask about the Iridium library, is it possible to use  clearBuffers
(ISBD_CLEAR_MO);  function, using Serial communication, not I2C

Thank you for your attention,
Giovani Ega

Pada tanggal Jum, 14 Okt 2022 pukul 16.25 Giovani Ega <
***@***.***> menulis:

**Comment by PaulZC** [comment]
Hello Giovani (@giovaniega ),

Greetings from the UK!

Yes, ```clearBuffers``` will work on Serial too. Your code will be like [Example6 for Serial](https://github.com/sparkfun/SparkFun_IridiumSBD_I2C_Arduino_Library/blob/main/examples/Serial_Examples__RockBLOCK/Example6_SendReceive/Example6_SendReceive.ino).

https://github.com/sparkfun/SparkFun_IridiumSBD_I2C_Arduino_Library/blob/5f8ea893907ba39e85d665abedc35ac09eb3567d/examples/Serial_Examples__RockBLOCK/Example6_SendReceive/Example6_SendReceive.ino#L105

Best wishes,
Paul
