### ISSUE TITLE
Feature request: adjustStartupTimeout()

### ISSUE THREAD

**Issue by adamgarbo** [sparkfun/SparkFun_IridiumSBD_I2C_Arduino_Library#3]
Hi @PaulZC,

I've found myself on several occasions needing to decrease the value of ISBD_STARTUP_MAX_TIME from 240 seconds to something shorter for testing or other purposes. This usually involves going in and modifying the library directly, but I was thinking that it could be useful to have a function that could set this timeout value directly.

Please let me know what you think! Happy to whip up a PR.

Cheers,
Adam

**Comment by PaulZC** [comment]
Hi @adamgarbo ,
Sure. We should have it default to ISBD_STARTUP_MAX_TIME, but maybe allow the user to change it via a function called ```setISBDstartupTime```? Please do submit a PR if you have time.
Thanks!
Paul

**Comment by PaulZC** [comment]
Closed by #4
