### ISSUE TITLE
Apollo3 Core v2.x incompatibility: WString.h is deprecated

### ISSUE THREAD

**Issue by adamgarbo** [sparkfun/SparkFun_IridiumSBD_I2C_Arduino_Library#5]
Hi @PaulZC,

I discovered today that v2.x of the Apollo3 Core is not compatible with the IridiumSBD I2C library, as it no longer includes WString.h. The core does include the following helpful note:

> // including WString.h is deprecated, for all future projects use Arduino.h instead

I'm not overly familiar with WString.h but it appears to be used extensively within the library. Should we try to have it included in the v2.x core or is Arduino.h capable of replacing its functionality?

Cheers,
Adam

**Comment by adamgarbo** [comment]
As a quick update, it appears that the SparkFun MicroMod nRF52840, which is based on the Arduino version of Mbed OS Core, also doesn't support this library. 

These new, fancy RTOS aren't making life easy! 

```
/Users/adam/Documents/Arduino/libraries/SparkFun_IridiumSBD_I2C_Arduino_Library/src/IridiumSBD.cpp: In member function 'int IridiumSBD::getSystemTime(tm&)':
/Users/adam/Documents/Arduino/libraries/SparkFun_IridiumSBD_I2C_Arduino_Library/src/IridiumSBD.cpp:235:9: error: 'F' was not declared in this scope
    send(F("AT-MSSTM\r"));
         ^
```

**Comment by PaulZC** [comment]
Hi Adam (@adamgarbo ),

Just ticking this one off the list...
I don't see the WString warning using v2.1.0 of the core. Maybe it was just a 2.0 thing?
And I hope the Flash helper string (F()) issue has gone away too? That's a biggie - and an issue for Arduino Mbed, not little old me...
I think we can close this, but please reopen if I've missed something.

Thanks!
Paul
