### ISSUE TITLE
ISBD_PROTOCOL_ERROR - More details?

### ISSUE THREAD

**Issue by adamgarbo** [sparkfun/SparkFun_IridiumSBD_I2C_Arduino_Library#6]
Hi @PaulZC,

I've been dealing with the dreaded "ISBD_PROTOCOL_ERROR" error recently with a RockBLOCK 9603, and I'm curious, is there a way to dig deeper into the IridiumSBD library to actually determine what's happening when presented with this error? Looking at the code, it appears to be somewhat of a catch-all error return code for a wide range of functions. 

Hmm, I do notice that it is most commonly associated with `!waitForATResponse`. I wonder if it my issue coudl be AT timeout-related. The RockBLOCK is powered directly by a 3.7 V LiPo and the supercapacitors are constantly charged, so everything should be snappy.

Cheers,
Adam

**Comment by PaulZC** [comment]
Hi Adam,
Do the diagprint's help? Change ```#define DIAGNOSTICS``` to ```true``` to enable them. You need the callbacks too - have a look at the bottom of the examples for details.
But, yes, unfortunately ISBD_PROTOCOL_ERROR is something of a catch-all badness-has-happened error. An AT timeout seems the likely cause.
How often are you getting the error? All the time, or occasionally? And are you using the Rock7 RockBLOCK 9603 - or the Qwiic Iridium?
Cheers,
Paul

**Comment by adamgarbo** [comment]
Thanks, Paul!

I've spent a lot of time looking at the Iridium diagnostics logs over the years, but the tricky thing is that these errors always seem to happen when the equipment is being tested outdoors and I can't watch the serial output. In this case, I'm using a RockBLOCK 9603 and the AT timeout is set to 20 seconds. 

So far, I've had 2/20 transmissions result in an error 3 (ISBD_PROTOCOL_ERROR). I'm now including the return code in the message that's being transmitted. The first error 3 occurred after attempting to transmit the message for 256 seconds (I usually only see 2 Iridium satellites where I am). The second error 3 occurred only after 24 seconds and is what worries me. Usually, I tend to get this error if I am not providing enough power to the RockBLOCK, but in this case, it should be able to draw as much as it needs from the 4.4 Ah LiPo. 

I'll keep digging!

**Comment by adamgarbo** [comment]
For some reason, I had thought that the default AT timeout was 20 seconds. However, looking closer at both the IridiumSBD I2C library and Mikal Hart's library, I see that it is in fact 30 seconds. 

Could setting the AT timeout to 20 seconds be the source of the ISBD_PROTOCOL_ERROR messages? Under ideal conditions, the wake-up, charge and transmit cycle takes only 12 seconds to complete. I most often notice that the error 3 failure occurs at the end of the first AT timeout (~24 seconds). It seems like the modem is getting hung up on something, but I'm really uncertain of what it could be.

**Comment by adamgarbo** [comment]
Hi Paul,

I believe the 20 seconds AT timeout may ultimately be the cause of the issues I was encoutnering. I've had a system test running for 48 hours now, transmitting every 1-3 hours, and haven't had a single ISBD_PROTOCOL_ERROR. For whatever reason, it seems 30 seconds the minimal timeout period.

I'll be doing lots of testing over the next few months and will open this issue back up if the dreaded error 3 reappears. 

Cheers,
Adam

**Comment by PaulZC** [comment]
That's great news Adam - thanks for letting me know,
All the best,
Paul
