### ISSUE TITLE
Compile errors for "time.h" for "epoch_start" and "local time" and "mtkime"

### ISSUE THREAD

**Issue by kenbiba** [sparkfun/SparkFun_IridiumSBD_I2C_Arduino_Library#7]
I suspect that I have a mismatch in my Time.h library for this driver.

Can someone help point me to the right library or an updated version of the Iridium Driver?

K

**Comment by PaulZC** [comment]
Hi @kenbiba,
This IridiumSBD library uses the standard Arduino time library (built-in). You will probably run into problems if you have other time libraries installed? Like [Paul Stoffregen's time](https://github.com/PaulStoffregen/Time) library?
Which platform/board are you using?
Please close if this resolves your issue.
Best wishes,
Paul

**Comment by kenbiba** [comment]
Hmmmm ... it seems my time library might me non-standard ... it redirects to something called timelib.h.  Hmmm it appears I have Paul's library installed ... I wonder why?   OK.   need to flush libraries and see if that fixes things.   Thanks.
