### ISSUE TITLE
No need to remove unused data after a Wire.requestFrom().

### ISSUE THREAD

**Issue by Koepel** [sparkfun/SparkFun_IridiumSBD_I2C_Arduino_Library#8]
In the file "IridiumSBD.cpp", currently at line 1403, there is this code:
```
while (wireport->available())
{
  wireport->read(); // Mop up any unexpected bytes
}
```
That code can be removed, since the Wire library uses packages of data and not a stream of data. There is no need to remove unused data.

Explanation: [Common-mistakes#4](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes#4)

In the code above that, is this:
```
wireport->requestFrom((uint8_t)deviceaddress, 2); // Request two bytes
if (wireport->available() >= 2)
```
The peripheral can not send less or more. There is no need to allow that it is higher than 2.
If two bytes are requested, then test for two bytes:
```
if (wireport->available() == 2)
```

**Comment by PaulZC** [comment]
Thank you @Koepel ,
Changed in [this commit](https://github.com/sparkfun/SparkFun_IridiumSBD_I2C_Arduino_Library/commit/020aeeea6f5d7fd82fc474ba00163953aa210d13). I will include the changes in the next release after testing.
Best wishes,
Paul
